site_name: Manual de Administrador – Edu 2.0

theme:
  name: material
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - palette.toggle
    - navigation.sections
    - content.code.copy

extra_javascript:
  - js/logo-theme-switcher.js
markdown_extensions:
  - attr_list

nav:
  - Introducción: index.md
  - Arquitectura: arquitectura.md
  - Requerimientos: requerimientos.md
  - Instalación:
      - Preparación del entorno: preparación-entorno.md
      - Backend: instalacion-backend.md
      - Frontend: instalacion-frontend.md
  - Bases de datos:
      - Configuración: base-datos.md
      - MongoDB en Docker: mongodb-docker.md
  - Servidor LLM: servidor-llm.md
  - Automatización: automatizacion.md
  - Administración: administracion.md
  - Seguridad: seguridad.md
  - Copias de seguridad: backups.md
  - Migración: migracion.md
  - FAQ: faq.md
  - Acerca de Smartech: acerca.md

dev_addr: 127.0.0.1:8001
